; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27032.1 

	TITLE	C:\Users\unm\Documents\GitHub\caCode\src\failSafeC\GeneratedFiles\Release\moc_qCheckOutputVPage.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

EXTRN	__imp_?staticMetaObject@QWizardPage@@2UQMetaObject@@B:BYTE
CONST	SEGMENT
?qt_meta_stringdata_qCheckOutputVPage@@3Uqt_meta_stringdata_qCheckOutputVPage_t@@B DD 0ffffffffH ; qt_meta_stringdata_qCheckOutputVPage
	DD	011H
	DD	00H
	DD	070H
	DD	0ffffffffH
	DD	015H
	DD	00H
	DD	072H
	DD	0ffffffffH
	DD	00H
	DD	00H
	DD	078H
	DD	0ffffffffH
	DD	012H
	DD	00H
	DD	069H
	DD	0ffffffffH
	DD	011H
	DD	00H
	DD	06cH
	DD	0ffffffffH
	DD	010H
	DD	00H
	DD	06eH
	DD	0ffffffffH
	DD	07H
	DD	00H
	DD	06fH
	DB	071H
	DB	043H
	DB	068H
	DB	065H
	DB	063H
	DB	06bH
	DB	04fH
	DB	075H
	DB	074H
	DB	070H
	DB	075H
	DB	074H
	DB	056H
	DB	050H
	DB	061H
	DB	067H
	DB	065H
	DB	00H
	DB	070H
	DB	061H
	DB	072H
	DB	065H
	DB	06eH
	DB	074H
	DB	043H
	DB	06fH
	DB	06dH
	DB	070H
	DB	06cH
	DB	065H
	DB	074H
	DB	065H
	DB	043H
	DB	068H
	DB	061H
	DB	06eH
	DB	067H
	DB	065H
	DB	064H
	DB	00H
	DB	00H
	DB	06fH
	DB	06eH
	DB	041H
	DB	06cH
	DB	06cH
	DB	054H
	DB	068H
	DB	072H
	DB	065H
	DB	061H
	DB	064H
	DB	053H
	DB	074H
	DB	061H
	DB	072H
	DB	074H
	DB	065H
	DB	064H
	DB	00H
	DB	06fH
	DB	06eH
	DB	053H
	DB	074H
	DB	061H
	DB	072H
	DB	074H
	DB	042H
	DB	074H
	DB	06eH
	DB	043H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	DB	06fH
	DB	06eH
	DB	053H
	DB	074H
	DB	06fH
	DB	070H
	DB	042H
	DB	074H
	DB	06eH
	DB	043H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	DB	061H
	DB	063H
	DB	071H
	DB	044H
	DB	06fH
	DB	06eH
	DB	065H
	DB	00H
	ORG $+1
?qt_meta_data_qCheckOutputVPage@@3QBIB DD 08H		; qt_meta_data_qCheckOutputVPage
	DD	00H
	DD	00H
	DD	00H
	DD	05H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	01H
	DD	00H
	DD	027H
	DD	02H
	DD	06H
	DD	03H
	DD	00H
	DD	028H
	DD	02H
	DD	08H
	DD	04H
	DD	00H
	DD	029H
	DD	02H
	DD	08H
	DD	05H
	DD	00H
	DD	02aH
	DD	02H
	DD	08H
	DD	06H
	DD	00H
	DD	02bH
	DD	02H
	DD	08H
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	00H
CONST	ENDS
PUBLIC	?metaObject@qCheckOutputVPage@@UBEPBUQMetaObject@@XZ ; qCheckOutputVPage::metaObject
PUBLIC	?qt_metacast@qCheckOutputVPage@@UAEPAXPBD@Z	; qCheckOutputVPage::qt_metacast
PUBLIC	?qt_metacall@qCheckOutputVPage@@UAEHW4Call@QMetaObject@@HPAPAX@Z ; qCheckOutputVPage::qt_metacall
PUBLIC	?qt_static_metacall@qCheckOutputVPage@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z ; qCheckOutputVPage::qt_static_metacall
PUBLIC	?parentCompleteChanged@qCheckOutputVPage@@QAEXXZ ; qCheckOutputVPage::parentCompleteChanged
PUBLIC	?staticMetaObject@qCheckOutputVPage@@2UQMetaObject@@B ; qCheckOutputVPage::staticMetaObject
EXTRN	__imp_?activate@QMetaObject@@SAXPAVQObject@@PBU1@HPAPAX@Z:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QBEPAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QWizardPage@@UAEPAXPBD@Z:PROC
EXTRN	__imp_?qt_metacall@QWizardPage@@UAEHW4Call@QMetaObject@@HPAPAX@Z:PROC
EXTRN	?onAllThreadStarted@qCheckOutputVPage@@AAEXXZ:PROC ; qCheckOutputVPage::onAllThreadStarted
EXTRN	?onStartBtnClicked@qCheckOutputVPage@@AAEXXZ:PROC ; qCheckOutputVPage::onStartBtnClicked
EXTRN	?onStopBtnClicked@qCheckOutputVPage@@AAEXXZ:PROC ; qCheckOutputVPage::onStopBtnClicked
EXTRN	?acqDone@qCheckOutputVPage@@AAEXXZ:PROC		; qCheckOutputVPage::acqDone
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@qCheckOutputVPage@@2P6AXXZA@@3P6AXXZA DD FLAT:??__E?staticMetaObject@qCheckOutputVPage@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@qCheckOutputVPage@@2P6AXXZA@@3P6AXXZA
CRT$XCU	ENDS
_DATA	SEGMENT
?staticMetaObject@qCheckOutputVPage@@2UQMetaObject@@B DB 4 DUP(00H) ; qCheckOutputVPage::staticMetaObject
	DD	FLAT:?qt_meta_stringdata_qCheckOutputVPage@@3Uqt_meta_stringdata_qCheckOutputVPage_t@@B
	DD	FLAT:?qt_meta_data_qCheckOutputVPage@@3QBIB
	DD	FLAT:?qt_static_metacall@qCheckOutputVPage@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z
	DD	00H
	DD	00H
_DATA	ENDS
; Function compile flags: /Ogtp
;	COMDAT ??__E?staticMetaObject@qCheckOutputVPage@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@qCheckOutputVPage@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'qCheckOutputVPage::staticMetaObject'', COMDAT
; File c:\users\unm\documents\github\cacode\src\failsafec\generatedfiles\release\moc_qcheckoutputvpage.cpp
; Line 111
	mov	eax, DWORD PTR __imp_?staticMetaObject@QWizardPage@@2UQMetaObject@@B
	mov	DWORD PTR ?staticMetaObject@qCheckOutputVPage@@2UQMetaObject@@B, eax
; Line 116
	ret	0
??__E?staticMetaObject@qCheckOutputVPage@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'qCheckOutputVPage::staticMetaObject''
text$di	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?parentCompleteChanged@qCheckOutputVPage@@QAEXXZ
_TEXT	SEGMENT
?parentCompleteChanged@qCheckOutputVPage@@QAEXXZ PROC	; qCheckOutputVPage::parentCompleteChanged, COMDAT
; _this$ = ecx
; File c:\users\unm\documents\github\cacode\src\failsafec\generatedfiles\release\moc_qcheckoutputvpage.cpp
; Line 153
	push	0
	push	0
	push	OFFSET ?staticMetaObject@qCheckOutputVPage@@2UQMetaObject@@B ; qCheckOutputVPage::staticMetaObject
	push	ecx
	call	DWORD PTR __imp_?activate@QMetaObject@@SAXPAVQObject@@PBU1@HPAPAX@Z
	add	esp, 16					; 00000010H
; Line 154
	ret	0
?parentCompleteChanged@qCheckOutputVPage@@QAEXXZ ENDP	; qCheckOutputVPage::parentCompleteChanged
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?qt_static_metacall@qCheckOutputVPage@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z
_TEXT	SEGMENT
__o$ = 8						; size = 4
__c$ = 12						; size = 4
__id$ = 16						; size = 4
__a$ = 20						; size = 4
?qt_static_metacall@qCheckOutputVPage@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z PROC ; qCheckOutputVPage::qt_static_metacall, COMDAT
; File c:\users\unm\documents\github\cacode\src\failsafec\generatedfiles\release\moc_qcheckoutputvpage.cpp
; Line 85
	push	ebp
	mov	ebp, esp
; Line 86
	mov	eax, DWORD PTR __c$[ebp]
	test	eax, eax
	jne	SHORT $LN4@qt_static_
; Line 89
	mov	eax, DWORD PTR __id$[ebp]
	cmp	eax, 4
	ja	SHORT $LN13@qt_static_
	jmp	DWORD PTR $LN24@qt_static_[eax*4]
$LN6@qt_static_:
; Line 153
	mov	DWORD PTR __a$[ebp], 0
	mov	DWORD PTR __id$[ebp], 0
	mov	DWORD PTR __c$[ebp], OFFSET ?staticMetaObject@qCheckOutputVPage@@2UQMetaObject@@B ; qCheckOutputVPage::staticMetaObject
; Line 108
	pop	ebp
; Line 153
	jmp	DWORD PTR __imp_?activate@QMetaObject@@SAXPAVQObject@@PBU1@HPAPAX@Z
$LN7@qt_static_:
; Line 91
	mov	ecx, DWORD PTR __o$[ebp]
; Line 108
	pop	ebp
; Line 91
	jmp	?onAllThreadStarted@qCheckOutputVPage@@AAEXXZ ; qCheckOutputVPage::onAllThreadStarted
$LN8@qt_static_:
; Line 92
	mov	ecx, DWORD PTR __o$[ebp]
; Line 108
	pop	ebp
; Line 92
	jmp	?onStartBtnClicked@qCheckOutputVPage@@AAEXXZ ; qCheckOutputVPage::onStartBtnClicked
$LN9@qt_static_:
; Line 93
	mov	ecx, DWORD PTR __o$[ebp]
; Line 108
	pop	ebp
; Line 93
	jmp	?onStopBtnClicked@qCheckOutputVPage@@AAEXXZ ; qCheckOutputVPage::onStopBtnClicked
$LN10@qt_static_:
; Line 94
	mov	ecx, DWORD PTR __o$[ebp]
; Line 108
	pop	ebp
; Line 94
	jmp	?acqDone@qCheckOutputVPage@@AAEXXZ	; qCheckOutputVPage::acqDone
$LN4@qt_static_:
; Line 97
	cmp	eax, 10					; 0000000aH
	jne	SHORT $LN13@qt_static_
; Line 98
	mov	eax, DWORD PTR __a$[ebp]
	mov	edx, DWORD PTR [eax]
; Line 101
	mov	eax, DWORD PTR [eax+4]
	mov	ecx, DWORD PTR [eax]
	cmp	ecx, OFFSET ?parentCompleteChanged@qCheckOutputVPage@@QAEXXZ ; qCheckOutputVPage::parentCompleteChanged
	jne	SHORT $LN13@qt_static_
	test	ecx, ecx
	je	SHORT $LN20@qt_static_
	cmp	DWORD PTR [eax+4], 0
	jne	SHORT $LN13@qt_static_
$LN20@qt_static_:
; Line 102
	mov	DWORD PTR [edx], 0
$LN13@qt_static_:
; Line 108
	pop	ebp
	ret	0
	npad	2
$LN24@qt_static_:
	DD	$LN6@qt_static_
	DD	$LN7@qt_static_
	DD	$LN8@qt_static_
	DD	$LN9@qt_static_
	DD	$LN10@qt_static_
?qt_static_metacall@qCheckOutputVPage@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z ENDP ; qCheckOutputVPage::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?qt_metacall@qCheckOutputVPage@@UAEHW4Call@QMetaObject@@HPAPAX@Z
_TEXT	SEGMENT
_this$1$ = -4						; size = 4
__c$ = 8						; size = 4
__id$ = 12						; size = 4
__a$ = 16						; size = 4
?qt_metacall@qCheckOutputVPage@@UAEHW4Call@QMetaObject@@HPAPAX@Z PROC ; qCheckOutputVPage::qt_metacall, COMDAT
; _this$ = ecx
; File c:\users\unm\documents\github\cacode\src\failsafec\generatedfiles\release\moc_qcheckoutputvpage.cpp
; Line 134
	push	ebp
	mov	ebp, esp
	push	ecx
	push	ebx
; Line 135
	mov	ebx, DWORD PTR __a$[ebp]
	mov	eax, ecx
	push	esi
	push	edi
	mov	edi, DWORD PTR __c$[ebp]
	push	ebx
	push	DWORD PTR __id$[ebp]
	mov	DWORD PTR _this$1$[ebp], eax
	push	edi
	call	DWORD PTR __imp_?qt_metacall@QWizardPage@@UAEHW4Call@QMetaObject@@HPAPAX@Z
	mov	esi, eax
; Line 136
	test	esi, esi
	js	SHORT $LN1@qt_metacal
; Line 138
	test	edi, edi
	jne	SHORT $LN3@qt_metacal
; Line 139
	cmp	esi, 5
	jge	SHORT $LN7@qt_metacal
; Line 140
	push	ebx
	push	esi
	push	edi
	push	DWORD PTR _this$1$[ebp]
	call	?qt_static_metacall@qCheckOutputVPage@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z ; qCheckOutputVPage::qt_static_metacall
	add	esp, 16					; 00000010H
; Line 147
	sub	esi, 5
	mov	eax, esi
	pop	edi
; Line 148
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
$LN3@qt_metacal:
; Line 142
	cmp	edi, 12					; 0000000cH
	jne	SHORT $LN6@qt_metacal
; Line 143
	cmp	esi, 5
	jge	SHORT $LN7@qt_metacal
; Line 144
	mov	eax, DWORD PTR [ebx]
	mov	DWORD PTR [eax], -1
$LN7@qt_metacal:
; Line 147
	sub	esi, 5
$LN6@qt_metacal:
	mov	eax, esi
$LN1@qt_metacal:
	pop	edi
; Line 148
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
?qt_metacall@qCheckOutputVPage@@UAEHW4Call@QMetaObject@@HPAPAX@Z ENDP ; qCheckOutputVPage::qt_metacall
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?qt_metacast@qCheckOutputVPage@@UAEPAXPBD@Z
_TEXT	SEGMENT
__clname$ = 8						; size = 4
?qt_metacast@qCheckOutputVPage@@UAEPAXPBD@Z PROC	; qCheckOutputVPage::qt_metacast, COMDAT
; _this$ = ecx
; File c:\users\unm\documents\github\cacode\src\failsafec\generatedfiles\release\moc_qcheckoutputvpage.cpp
; Line 126
	push	ebp
	mov	ebp, esp
	push	esi
; Line 127
	mov	esi, DWORD PTR __clname$[ebp]
	push	edi
	mov	edi, ecx
	test	esi, esi
	jne	SHORT $LN2@qt_metacas
	pop	edi
	xor	eax, eax
; Line 131
	pop	esi
	pop	ebp
	ret	4
$LN2@qt_metacas:
; Line 128
	mov	eax, OFFSET ?qt_meta_stringdata_qCheckOutputVPage@@3Uqt_meta_stringdata_qCheckOutputVPage_t@@B+112
	mov	ecx, esi
	npad	3
$LL5@qt_metacas:
	mov	dl, BYTE PTR [ecx]
	cmp	dl, BYTE PTR [eax]
	jne	SHORT $LN6@qt_metacas
	test	dl, dl
	je	SHORT $LN7@qt_metacas
	mov	dl, BYTE PTR [ecx+1]
	cmp	dl, BYTE PTR [eax+1]
	jne	SHORT $LN6@qt_metacas
	add	ecx, 2
	add	eax, 2
	test	dl, dl
	jne	SHORT $LL5@qt_metacas
$LN7@qt_metacas:
	xor	eax, eax
	jmp	SHORT $LN8@qt_metacas
$LN6@qt_metacas:
	sbb	eax, eax
	or	eax, 1
$LN8@qt_metacas:
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 129
	mov	eax, edi
	pop	edi
; Line 131
	pop	esi
	pop	ebp
	ret	4
$LN3@qt_metacas:
; Line 130
	push	esi
	mov	ecx, edi
	call	DWORD PTR __imp_?qt_metacast@QWizardPage@@UAEPAXPBD@Z
	pop	edi
; Line 131
	pop	esi
	pop	ebp
	ret	4
?qt_metacast@qCheckOutputVPage@@UAEPAXPBD@Z ENDP	; qCheckOutputVPage::qt_metacast
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?metaObject@qCheckOutputVPage@@UBEPBUQMetaObject@@XZ
_TEXT	SEGMENT
?metaObject@qCheckOutputVPage@@UBEPBUQMetaObject@@XZ PROC ; qCheckOutputVPage::metaObject, COMDAT
; _this$ = ecx
; File c:\users\unm\documents\github\cacode\src\failsafec\generatedfiles\release\moc_qcheckoutputvpage.cpp
; Line 122
	mov	ecx, DWORD PTR [ecx+4]
	cmp	DWORD PTR [ecx+24], 0
	je	SHORT $LN3@metaObject
	jmp	DWORD PTR __imp_?dynamicMetaObject@QObjectData@@QBEPAUQMetaObject@@XZ
$LN3@metaObject:
	mov	eax, OFFSET ?staticMetaObject@qCheckOutputVPage@@2UQMetaObject@@B ; qCheckOutputVPage::staticMetaObject
; Line 123
	ret	0
?metaObject@qCheckOutputVPage@@UBEPBUQMetaObject@@XZ ENDP ; qCheckOutputVPage::metaObject
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ
_TEXT	SEGMENT
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; _this$ = ecx
; File c:\qt\5.13.1\msvc2017\include\qtcore\qscopedpointer.h
; Line 118
	mov	eax, DWORD PTR [ecx]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
END
