; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27032.1 

	TITLE	C:\Users\unm\Documents\GitHub\caCode\src\failSafeC\GeneratedFiles\Release\moc_qSigGenThread.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

EXTRN	__imp_?staticMetaObject@QThread@@2UQMetaObject@@B:BYTE
CONST	SEGMENT
?qt_meta_stringdata_qSigGenThread@@3Uqt_meta_stringdata_qSigGenThread_t@@B DD 0ffffffffH ; qt_meta_stringdata_qSigGenThread
	DD	0dH
	DD	00H
	DD	040H
	DD	0ffffffffH
	DD	0bH
	DD	00H
	DD	03eH
	DD	0ffffffffH
	DD	00H
	DD	00H
	DD	03aH
	DD	0ffffffffH
	DD	0dH
	DD	00H
	DD	02bH
	DB	071H
	DB	053H
	DB	069H
	DB	067H
	DB	047H
	DB	065H
	DB	06eH
	DB	054H
	DB	068H
	DB	072H
	DB	065H
	DB	061H
	DB	064H
	DB	00H
	DB	041H
	DB	052H
	DB	042H
	DB	053H
	DB	065H
	DB	06cH
	DB	065H
	DB	063H
	DB	074H
	DB	065H
	DB	064H
	DB	00H
	DB	00H
	DB	074H
	DB	068H
	DB	072H
	DB	065H
	DB	061H
	DB	064H
	DB	053H
	DB	074H
	DB	061H
	DB	072H
	DB	074H
	DB	065H
	DB	064H
	DB	00H
	ORG $+3
	ORG $+4
?qt_meta_data_qSigGenThread@@3QBIB DD 08H		; qt_meta_data_qSigGenThread
	DD	00H
	DD	00H
	DD	00H
	DD	02H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	02H
	DD	01H
	DD	00H
	DD	018H
	DD	02H
	DD	06H
	DD	03H
	DD	00H
	DD	019H
	DD	02H
	DD	06H
	DD	02bH
	DD	02bH
	DD	00H
CONST	ENDS
PUBLIC	?metaObject@qSigGenThread@@UBEPBUQMetaObject@@XZ ; qSigGenThread::metaObject
PUBLIC	?qt_metacast@qSigGenThread@@UAEPAXPBD@Z		; qSigGenThread::qt_metacast
PUBLIC	?qt_metacall@qSigGenThread@@UAEHW4Call@QMetaObject@@HPAPAX@Z ; qSigGenThread::qt_metacall
PUBLIC	?qt_static_metacall@qSigGenThread@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z ; qSigGenThread::qt_static_metacall
PUBLIC	?ARBSelected@qSigGenThread@@QAEXXZ		; qSigGenThread::ARBSelected
PUBLIC	?threadStarted@qSigGenThread@@QAEXXZ		; qSigGenThread::threadStarted
PUBLIC	?staticMetaObject@qSigGenThread@@2UQMetaObject@@B ; qSigGenThread::staticMetaObject
EXTRN	__imp_?activate@QMetaObject@@SAXPAVQObject@@PBU1@HPAPAX@Z:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QBEPAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QThread@@UAEPAXPBD@Z:PROC
EXTRN	__imp_?qt_metacall@QThread@@UAEHW4Call@QMetaObject@@HPAPAX@Z:PROC
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@qSigGenThread@@2P6AXXZA@@3P6AXXZA DD FLAT:??__E?staticMetaObject@qSigGenThread@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@qSigGenThread@@2P6AXXZA@@3P6AXXZA
CRT$XCU	ENDS
_DATA	SEGMENT
?staticMetaObject@qSigGenThread@@2UQMetaObject@@B DB 4 DUP(00H) ; qSigGenThread::staticMetaObject
	DD	FLAT:?qt_meta_stringdata_qSigGenThread@@3Uqt_meta_stringdata_qSigGenThread_t@@B
	DD	FLAT:?qt_meta_data_qSigGenThread@@3QBIB
	DD	FLAT:?qt_static_metacall@qSigGenThread@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z
	DD	00H
	DD	00H
_DATA	ENDS
; Function compile flags: /Ogtp
;	COMDAT ??__E?staticMetaObject@qSigGenThread@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@qSigGenThread@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'qSigGenThread::staticMetaObject'', COMDAT
; File c:\users\unm\documents\github\cacode\src\failsafec\generatedfiles\release\moc_qsiggenthread.cpp
; Line 100
	mov	eax, DWORD PTR __imp_?staticMetaObject@QThread@@2UQMetaObject@@B
	mov	DWORD PTR ?staticMetaObject@qSigGenThread@@2UQMetaObject@@B, eax
; Line 105
	ret	0
??__E?staticMetaObject@qSigGenThread@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'qSigGenThread::staticMetaObject''
text$di	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?threadStarted@qSigGenThread@@QAEXXZ
_TEXT	SEGMENT
?threadStarted@qSigGenThread@@QAEXXZ PROC		; qSigGenThread::threadStarted, COMDAT
; _this$ = ecx
; File c:\users\unm\documents\github\cacode\src\failsafec\generatedfiles\release\moc_qsiggenthread.cpp
; Line 148
	push	0
	push	1
	push	OFFSET ?staticMetaObject@qSigGenThread@@2UQMetaObject@@B ; qSigGenThread::staticMetaObject
	push	ecx
	call	DWORD PTR __imp_?activate@QMetaObject@@SAXPAVQObject@@PBU1@HPAPAX@Z
	add	esp, 16					; 00000010H
; Line 149
	ret	0
?threadStarted@qSigGenThread@@QAEXXZ ENDP		; qSigGenThread::threadStarted
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?ARBSelected@qSigGenThread@@QAEXXZ
_TEXT	SEGMENT
?ARBSelected@qSigGenThread@@QAEXXZ PROC			; qSigGenThread::ARBSelected, COMDAT
; _this$ = ecx
; File c:\users\unm\documents\github\cacode\src\failsafec\generatedfiles\release\moc_qsiggenthread.cpp
; Line 142
	push	0
	push	0
	push	OFFSET ?staticMetaObject@qSigGenThread@@2UQMetaObject@@B ; qSigGenThread::staticMetaObject
	push	ecx
	call	DWORD PTR __imp_?activate@QMetaObject@@SAXPAVQObject@@PBU1@HPAPAX@Z
	add	esp, 16					; 00000010H
; Line 143
	ret	0
?ARBSelected@qSigGenThread@@QAEXXZ ENDP			; qSigGenThread::ARBSelected
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?qt_static_metacall@qSigGenThread@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z
_TEXT	SEGMENT
__o$ = 8						; size = 4
__c$ = 12						; size = 4
__id$ = 16						; size = 4
__a$ = 20						; size = 4
?qt_static_metacall@qSigGenThread@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z PROC ; qSigGenThread::qt_static_metacall, COMDAT
; File c:\users\unm\documents\github\cacode\src\failsafec\generatedfiles\release\moc_qsiggenthread.cpp
; Line 70
	push	ebp
	mov	ebp, esp
; Line 71
	mov	eax, DWORD PTR __c$[ebp]
	test	eax, eax
	jne	SHORT $LN4@qt_static_
; Line 74
	mov	eax, DWORD PTR __id$[ebp]
	sub	eax, 0
	je	SHORT $LN6@qt_static_
	sub	eax, 1
	jne	SHORT $LN11@qt_static_
; Line 148
	mov	DWORD PTR __a$[ebp], eax
	mov	DWORD PTR __id$[ebp], 1
	mov	DWORD PTR __c$[ebp], OFFSET ?staticMetaObject@qSigGenThread@@2UQMetaObject@@B ; qSigGenThread::staticMetaObject
; Line 97
	pop	ebp
; Line 148
	jmp	DWORD PTR __imp_?activate@QMetaObject@@SAXPAVQObject@@PBU1@HPAPAX@Z
$LN6@qt_static_:
; Line 142
	mov	DWORD PTR __a$[ebp], 0
	mov	DWORD PTR __id$[ebp], 0
	mov	DWORD PTR __c$[ebp], OFFSET ?staticMetaObject@qSigGenThread@@2UQMetaObject@@B ; qSigGenThread::staticMetaObject
; Line 97
	pop	ebp
; Line 142
	jmp	DWORD PTR __imp_?activate@QMetaObject@@SAXPAVQObject@@PBU1@HPAPAX@Z
$LN4@qt_static_:
; Line 79
	cmp	eax, 10					; 0000000aH
	jne	SHORT $LN11@qt_static_
; Line 80
	mov	eax, DWORD PTR __a$[ebp]
	mov	ecx, DWORD PTR [eax]
; Line 83
	mov	eax, DWORD PTR [eax+4]
	mov	eax, DWORD PTR [eax]
	cmp	eax, OFFSET ?ARBSelected@qSigGenThread@@QAEXXZ ; qSigGenThread::ARBSelected
	jne	SHORT $LN10@qt_static_
; Line 84
	mov	DWORD PTR [ecx], 0
; Line 97
	pop	ebp
	ret	0
$LN10@qt_static_:
; Line 90
	cmp	eax, OFFSET ?threadStarted@qSigGenThread@@QAEXXZ ; qSigGenThread::threadStarted
	jne	SHORT $LN11@qt_static_
; Line 91
	mov	DWORD PTR [ecx], 1
$LN11@qt_static_:
; Line 97
	pop	ebp
	ret	0
?qt_static_metacall@qSigGenThread@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z ENDP ; qSigGenThread::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?qt_metacall@qSigGenThread@@UAEHW4Call@QMetaObject@@HPAPAX@Z
_TEXT	SEGMENT
_this$1$ = -4						; size = 4
__c$ = 8						; size = 4
__id$ = 12						; size = 4
__a$ = 16						; size = 4
?qt_metacall@qSigGenThread@@UAEHW4Call@QMetaObject@@HPAPAX@Z PROC ; qSigGenThread::qt_metacall, COMDAT
; _this$ = ecx
; File c:\users\unm\documents\github\cacode\src\failsafec\generatedfiles\release\moc_qsiggenthread.cpp
; Line 123
	push	ebp
	mov	ebp, esp
	push	ecx
	push	ebx
; Line 124
	mov	ebx, DWORD PTR __a$[ebp]
	mov	eax, ecx
	push	esi
	push	edi
	mov	edi, DWORD PTR __c$[ebp]
	push	ebx
	push	DWORD PTR __id$[ebp]
	mov	DWORD PTR _this$1$[ebp], eax
	push	edi
	call	DWORD PTR __imp_?qt_metacall@QThread@@UAEHW4Call@QMetaObject@@HPAPAX@Z
	mov	esi, eax
; Line 125
	test	esi, esi
	js	SHORT $LN1@qt_metacal
; Line 127
	test	edi, edi
	jne	SHORT $LN3@qt_metacal
; Line 128
	cmp	esi, 2
	jge	SHORT $LN7@qt_metacal
; Line 129
	push	ebx
	push	esi
	push	edi
	push	DWORD PTR _this$1$[ebp]
	call	?qt_static_metacall@qSigGenThread@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z ; qSigGenThread::qt_static_metacall
	add	esp, 16					; 00000010H
; Line 136
	sub	esi, 2
	mov	eax, esi
	pop	edi
; Line 137
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
$LN3@qt_metacal:
; Line 131
	cmp	edi, 12					; 0000000cH
	jne	SHORT $LN6@qt_metacal
; Line 132
	cmp	esi, 2
	jge	SHORT $LN7@qt_metacal
; Line 133
	mov	eax, DWORD PTR [ebx]
	mov	DWORD PTR [eax], -1
$LN7@qt_metacal:
; Line 136
	sub	esi, 2
$LN6@qt_metacal:
	mov	eax, esi
$LN1@qt_metacal:
	pop	edi
; Line 137
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
?qt_metacall@qSigGenThread@@UAEHW4Call@QMetaObject@@HPAPAX@Z ENDP ; qSigGenThread::qt_metacall
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?qt_metacast@qSigGenThread@@UAEPAXPBD@Z
_TEXT	SEGMENT
__clname$ = 8						; size = 4
?qt_metacast@qSigGenThread@@UAEPAXPBD@Z PROC		; qSigGenThread::qt_metacast, COMDAT
; _this$ = ecx
; File c:\users\unm\documents\github\cacode\src\failsafec\generatedfiles\release\moc_qsiggenthread.cpp
; Line 115
	push	ebp
	mov	ebp, esp
	push	esi
; Line 116
	mov	esi, DWORD PTR __clname$[ebp]
	push	edi
	mov	edi, ecx
	test	esi, esi
	jne	SHORT $LN2@qt_metacas
	pop	edi
	xor	eax, eax
; Line 120
	pop	esi
	pop	ebp
	ret	4
$LN2@qt_metacas:
; Line 117
	mov	eax, OFFSET ?qt_meta_stringdata_qSigGenThread@@3Uqt_meta_stringdata_qSigGenThread_t@@B+64
	mov	ecx, esi
	npad	3
$LL5@qt_metacas:
	mov	dl, BYTE PTR [ecx]
	cmp	dl, BYTE PTR [eax]
	jne	SHORT $LN6@qt_metacas
	test	dl, dl
	je	SHORT $LN7@qt_metacas
	mov	dl, BYTE PTR [ecx+1]
	cmp	dl, BYTE PTR [eax+1]
	jne	SHORT $LN6@qt_metacas
	add	ecx, 2
	add	eax, 2
	test	dl, dl
	jne	SHORT $LL5@qt_metacas
$LN7@qt_metacas:
	xor	eax, eax
	jmp	SHORT $LN8@qt_metacas
$LN6@qt_metacas:
	sbb	eax, eax
	or	eax, 1
$LN8@qt_metacas:
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 118
	mov	eax, edi
	pop	edi
; Line 120
	pop	esi
	pop	ebp
	ret	4
$LN3@qt_metacas:
; Line 119
	push	esi
	mov	ecx, edi
	call	DWORD PTR __imp_?qt_metacast@QThread@@UAEPAXPBD@Z
	pop	edi
; Line 120
	pop	esi
	pop	ebp
	ret	4
?qt_metacast@qSigGenThread@@UAEPAXPBD@Z ENDP		; qSigGenThread::qt_metacast
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?metaObject@qSigGenThread@@UBEPBUQMetaObject@@XZ
_TEXT	SEGMENT
?metaObject@qSigGenThread@@UBEPBUQMetaObject@@XZ PROC	; qSigGenThread::metaObject, COMDAT
; _this$ = ecx
; File c:\users\unm\documents\github\cacode\src\failsafec\generatedfiles\release\moc_qsiggenthread.cpp
; Line 111
	mov	ecx, DWORD PTR [ecx+4]
	cmp	DWORD PTR [ecx+24], 0
	je	SHORT $LN3@metaObject
	jmp	DWORD PTR __imp_?dynamicMetaObject@QObjectData@@QBEPAUQMetaObject@@XZ
$LN3@metaObject:
	mov	eax, OFFSET ?staticMetaObject@qSigGenThread@@2UQMetaObject@@B ; qSigGenThread::staticMetaObject
; Line 112
	ret	0
?metaObject@qSigGenThread@@UBEPBUQMetaObject@@XZ ENDP	; qSigGenThread::metaObject
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ
_TEXT	SEGMENT
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; _this$ = ecx
; File c:\qt\5.13.1\msvc2017\include\qtcore\qscopedpointer.h
; Line 118
	mov	eax, DWORD PTR [ecx]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
END
