; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27032.1 

	TITLE	C:\Users\unm\Documents\GitHub\caCode\src\failSafeC\GeneratedFiles\Release\moc_qFailSafeWizard.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	?staticMetaObject@qRecord@@2UQMetaObject@@B	; qRecord::staticMetaObject
EXTRN	__imp_?staticMetaObject@QWizard@@2UQMetaObject@@B:BYTE
CONST	SEGMENT
?staticMetaObject@qRecord@@2UQMetaObject@@B DD 00H	; qRecord::staticMetaObject
	DD	FLAT:?qt_meta_stringdata_qRecord@@3Uqt_meta_stringdata_qRecord_t@@B
	DD	FLAT:?qt_meta_data_qRecord@@3QBIB
	DD	00H
	DD	00H
	DD	00H
?qt_meta_stringdata_qRecord@@3Uqt_meta_stringdata_qRecord_t@@B DD 0ffffffffH ; qt_meta_stringdata_qRecord
	DD	07H
	DD	00H
	DD	010H
	DB	071H
	DB	052H
	DB	065H
	DB	063H
	DB	06fH
	DB	072H
	DB	064H
	DB	00H
?qt_meta_data_qRecord@@3QBIB DD 08H			; qt_meta_data_qRecord
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	04H
	DD	00H
	DD	00H
?qt_meta_stringdata_qFailSafeWizard@@3Uqt_meta_stringdata_qFailSafeWizard_t@@B DD 0ffffffffH ; qt_meta_stringdata_qFailSafeWizard
	DD	0fH
	DD	00H
	DD	040H
	DD	0ffffffffH
	DD	04H
	DD	00H
	DD	040H
	DD	0ffffffffH
	DD	00H
	DD	00H
	DD	035H
	DD	0ffffffffH
	DD	06H
	DD	00H
	DD	026H
	DB	071H
	DB	046H
	DB	061H
	DB	069H
	DB	06cH
	DB	053H
	DB	061H
	DB	066H
	DB	065H
	DB	057H
	DB	069H
	DB	07aH
	DB	061H
	DB	072H
	DB	064H
	DB	00H
	DB	064H
	DB	06fH
	DB	06eH
	DB	065H
	DB	00H
	DB	00H
	DB	072H
	DB	065H
	DB	073H
	DB	075H
	DB	06cH
	DB	074H
	DB	00H
	ORG $+3
	ORG $+4
?qt_meta_data_qFailSafeWizard@@3QBIB DD 08H		; qt_meta_data_qFailSafeWizard
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	01H
	DD	013H
	DD	02H
	DD	0aH
	DD	02bH
	DD	02H
	DD	03H
	DD	00H
CONST	ENDS
PUBLIC	?metaObject@qFailSafeWizard@@UBEPBUQMetaObject@@XZ ; qFailSafeWizard::metaObject
PUBLIC	?qt_metacast@qFailSafeWizard@@UAEPAXPBD@Z	; qFailSafeWizard::qt_metacast
PUBLIC	?qt_metacall@qFailSafeWizard@@UAEHW4Call@QMetaObject@@HPAPAX@Z ; qFailSafeWizard::qt_metacall
PUBLIC	?qt_static_metacall@qFailSafeWizard@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z ; qFailSafeWizard::qt_static_metacall
PUBLIC	?staticMetaObject@qFailSafeWizard@@2UQMetaObject@@B ; qFailSafeWizard::staticMetaObject
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QBEPAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QWizard@@UAEPAXPBD@Z:PROC
EXTRN	__imp_?qt_metacall@QWizard@@UAEHW4Call@QMetaObject@@HPAPAX@Z:PROC
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@qFailSafeWizard@@2P6AXXZA@@3P6AXXZA DD FLAT:??__E?staticMetaObject@qFailSafeWizard@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@qFailSafeWizard@@2P6AXXZA@@3P6AXXZA
CRT$XCU	ENDS
_DATA	SEGMENT
?staticMetaObject@qFailSafeWizard@@2UQMetaObject@@B DB 4 DUP(00H) ; qFailSafeWizard::staticMetaObject
	DD	FLAT:?qt_meta_stringdata_qFailSafeWizard@@3Uqt_meta_stringdata_qFailSafeWizard_t@@B
	DD	FLAT:?qt_meta_data_qFailSafeWizard@@3QBIB
	DD	FLAT:?qt_static_metacall@qFailSafeWizard@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z
	DD	00H
	DD	00H
_DATA	ENDS
; Function compile flags: /Ogtp
;	COMDAT ??__E?staticMetaObject@qFailSafeWizard@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@qFailSafeWizard@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'qFailSafeWizard::staticMetaObject'', COMDAT
; File c:\users\unm\documents\github\cacode\src\failsafec\generatedfiles\release\moc_qfailsafewizard.cpp
; Line 123
	mov	eax, DWORD PTR __imp_?staticMetaObject@QWizard@@2UQMetaObject@@B
	mov	DWORD PTR ?staticMetaObject@qFailSafeWizard@@2UQMetaObject@@B, eax
; Line 128
	ret	0
??__E?staticMetaObject@qFailSafeWizard@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'qFailSafeWizard::staticMetaObject''
text$di	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?qt_static_metacall@qFailSafeWizard@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z
_TEXT	SEGMENT
__o$ = 8						; size = 4
__c$ = 12						; size = 4
__id$ = 16						; size = 4
__a$ = 20						; size = 4
?qt_static_metacall@qFailSafeWizard@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z PROC ; qFailSafeWizard::qt_static_metacall, COMDAT
; File c:\users\unm\documents\github\cacode\src\failsafec\generatedfiles\release\moc_qfailsafewizard.cpp
; Line 111
	push	ebp
	mov	ebp, esp
; Line 112
	cmp	DWORD PTR __c$[ebp], 0
	jne	SHORT $LN6@qt_static_
; Line 115
	cmp	DWORD PTR __id$[ebp], 0
	jne	SHORT $LN6@qt_static_
; Line 116
	mov	eax, DWORD PTR __a$[ebp]
	mov	ecx, DWORD PTR __o$[ebp]
	mov	eax, DWORD PTR [eax+4]
	mov	edx, DWORD PTR [ecx]
	push	DWORD PTR [eax]
	call	DWORD PTR [edx+188]
$LN6@qt_static_:
; Line 120
	pop	ebp
	ret	0
?qt_static_metacall@qFailSafeWizard@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z ENDP ; qFailSafeWizard::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?qt_metacall@qFailSafeWizard@@UAEHW4Call@QMetaObject@@HPAPAX@Z
_TEXT	SEGMENT
_this$1$ = -4						; size = 4
__c$ = 8						; size = 4
__id$ = 12						; size = 4
__a$ = 16						; size = 4
?qt_metacall@qFailSafeWizard@@UAEHW4Call@QMetaObject@@HPAPAX@Z PROC ; qFailSafeWizard::qt_metacall, COMDAT
; _this$ = ecx
; File c:\users\unm\documents\github\cacode\src\failsafec\generatedfiles\release\moc_qfailsafewizard.cpp
; Line 146
	push	ebp
	mov	ebp, esp
	push	ecx
	push	ebx
; Line 147
	mov	ebx, DWORD PTR __a$[ebp]
	mov	eax, ecx
	push	esi
	push	edi
	mov	edi, DWORD PTR __c$[ebp]
	push	ebx
	push	DWORD PTR __id$[ebp]
	mov	DWORD PTR _this$1$[ebp], eax
	push	edi
	call	DWORD PTR __imp_?qt_metacall@QWizard@@UAEHW4Call@QMetaObject@@HPAPAX@Z
	mov	esi, eax
; Line 148
	test	esi, esi
	js	SHORT $LN1@qt_metacal
; Line 150
	test	edi, edi
	jne	SHORT $LN3@qt_metacal
; Line 151
	cmp	esi, 1
	jge	SHORT $LN7@qt_metacal
; Line 115
	test	esi, esi
	jne	SHORT $LN7@qt_metacal
; Line 116
	mov	ecx, DWORD PTR _this$1$[ebp]
	mov	eax, DWORD PTR [ebx+4]
	mov	edx, DWORD PTR [ecx]
	push	DWORD PTR [eax]
	call	DWORD PTR [edx+188]
; Line 159
	dec	esi
	pop	edi
	mov	eax, esi
; Line 160
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
$LN3@qt_metacal:
; Line 154
	cmp	edi, 12					; 0000000cH
	jne	SHORT $LN6@qt_metacal
; Line 155
	cmp	esi, 1
	jge	SHORT $LN7@qt_metacal
; Line 156
	mov	eax, DWORD PTR [ebx]
	mov	DWORD PTR [eax], -1
$LN7@qt_metacal:
; Line 159
	dec	esi
$LN6@qt_metacal:
	mov	eax, esi
$LN1@qt_metacal:
	pop	edi
; Line 160
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
?qt_metacall@qFailSafeWizard@@UAEHW4Call@QMetaObject@@HPAPAX@Z ENDP ; qFailSafeWizard::qt_metacall
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?qt_metacast@qFailSafeWizard@@UAEPAXPBD@Z
_TEXT	SEGMENT
__clname$ = 8						; size = 4
?qt_metacast@qFailSafeWizard@@UAEPAXPBD@Z PROC		; qFailSafeWizard::qt_metacast, COMDAT
; _this$ = ecx
; File c:\users\unm\documents\github\cacode\src\failsafec\generatedfiles\release\moc_qfailsafewizard.cpp
; Line 138
	push	ebp
	mov	ebp, esp
	push	esi
; Line 139
	mov	esi, DWORD PTR __clname$[ebp]
	push	edi
	mov	edi, ecx
	test	esi, esi
	jne	SHORT $LN2@qt_metacas
	pop	edi
	xor	eax, eax
; Line 143
	pop	esi
	pop	ebp
	ret	4
$LN2@qt_metacas:
; Line 140
	mov	eax, OFFSET ?qt_meta_stringdata_qFailSafeWizard@@3Uqt_meta_stringdata_qFailSafeWizard_t@@B+64
	mov	ecx, esi
	npad	3
$LL5@qt_metacas:
	mov	dl, BYTE PTR [ecx]
	cmp	dl, BYTE PTR [eax]
	jne	SHORT $LN6@qt_metacas
	test	dl, dl
	je	SHORT $LN7@qt_metacas
	mov	dl, BYTE PTR [ecx+1]
	cmp	dl, BYTE PTR [eax+1]
	jne	SHORT $LN6@qt_metacas
	add	ecx, 2
	add	eax, 2
	test	dl, dl
	jne	SHORT $LL5@qt_metacas
$LN7@qt_metacas:
	xor	eax, eax
	jmp	SHORT $LN8@qt_metacas
$LN6@qt_metacas:
	sbb	eax, eax
	or	eax, 1
$LN8@qt_metacas:
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 141
	mov	eax, edi
	pop	edi
; Line 143
	pop	esi
	pop	ebp
	ret	4
$LN3@qt_metacas:
; Line 142
	push	esi
	mov	ecx, edi
	call	DWORD PTR __imp_?qt_metacast@QWizard@@UAEPAXPBD@Z
	pop	edi
; Line 143
	pop	esi
	pop	ebp
	ret	4
?qt_metacast@qFailSafeWizard@@UAEPAXPBD@Z ENDP		; qFailSafeWizard::qt_metacast
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?metaObject@qFailSafeWizard@@UBEPBUQMetaObject@@XZ
_TEXT	SEGMENT
?metaObject@qFailSafeWizard@@UBEPBUQMetaObject@@XZ PROC	; qFailSafeWizard::metaObject, COMDAT
; _this$ = ecx
; File c:\users\unm\documents\github\cacode\src\failsafec\generatedfiles\release\moc_qfailsafewizard.cpp
; Line 134
	mov	ecx, DWORD PTR [ecx+4]
	cmp	DWORD PTR [ecx+24], 0
	je	SHORT $LN3@metaObject
	jmp	DWORD PTR __imp_?dynamicMetaObject@QObjectData@@QBEPAUQMetaObject@@XZ
$LN3@metaObject:
	mov	eax, OFFSET ?staticMetaObject@qFailSafeWizard@@2UQMetaObject@@B ; qFailSafeWizard::staticMetaObject
; Line 135
	ret	0
?metaObject@qFailSafeWizard@@UBEPBUQMetaObject@@XZ ENDP	; qFailSafeWizard::metaObject
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ
_TEXT	SEGMENT
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; _this$ = ecx
; File c:\qt\5.13.1\msvc2017\include\qtcore\qscopedpointer.h
; Line 118
	mov	eax, DWORD PTR [ecx]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
END
