; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27032.1 

	TITLE	C:\Users\unm\Documents\GitHub\caCode\src\failSafeC\GeneratedFiles\Release\moc_qSanityChkDlg.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

EXTRN	__imp_?staticMetaObject@QDialog@@2UQMetaObject@@B:BYTE
CONST	SEGMENT
?qt_meta_stringdata_qSanityChkDlg@@3Uqt_meta_stringdata_qSanityChkDlg_t@@B DD 0ffffffffH ; qt_meta_stringdata_qSanityChkDlg
	DD	0dH
	DD	00H
	DD	0e0H
	DD	0ffffffffH
	DD	06H
	DD	00H
	DD	0deH
	DD	0ffffffffH
	DD	00H
	DD	00H
	DD	0d5H
	DD	0ffffffffH
	DD	06H
	DD	00H
	DD	0c6H
	DD	0ffffffffH
	DD	0dH
	DD	00H
	DD	0bdH
	DD	0ffffffffH
	DD	06H
	DD	00H
	DD	0bbH
	DD	0ffffffffH
	DD	010H
	DD	00H
	DD	0b2H
	DD	0ffffffffH
	DD	0cH
	DD	00H
	DD	0b3H
	DD	0ffffffffH
	DD	06H
	DD	00H
	DD	0b0H
	DD	0ffffffffH
	DD	0dH
	DD	00H
	DD	0a7H
	DD	0ffffffffH
	DD	0aH
	DD	00H
	DD	0a5H
	DD	0ffffffffH
	DD	013H
	DD	00H
	DD	0a0H
	DD	0ffffffffH
	DD	0cH
	DD	00H
	DD	0a4H
	DD	0ffffffffH
	DD	0bH
	DD	00H
	DD	0a1H
	DB	071H
	DB	053H
	DB	061H
	DB	06eH
	DB	069H
	DB	074H
	DB	079H
	DB	043H
	DB	068H
	DB	06bH
	DB	044H
	DB	06cH
	DB	067H
	DB	00H
	DB	061H
	DB	063H
	DB	063H
	DB	065H
	DB	070H
	DB	074H
	DB	00H
	DB	00H
	DB	072H
	DB	065H
	DB	06aH
	DB	065H
	DB	063H
	DB	074H
	DB	00H
	DB	06fH
	DB	06eH
	DB	052H
	DB	065H
	DB	06cH
	DB	061H
	DB	079H
	DB	04fH
	DB	070H
	DB	065H
	DB	06eH
	DB	065H
	DB	064H
	DB	00H
	DB	069H
	DB	073H
	DB	04fH
	DB	070H
	DB	065H
	DB	06eH
	DB	00H
	DB	06fH
	DB	06eH
	DB	054H
	DB	065H
	DB	073H
	DB	074H
	DB	042H
	DB	074H
	DB	06eH
	DB	043H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	DB	068H
	DB	061H
	DB	06eH
	DB	064H
	DB	06cH
	DB	065H
	DB	045H
	DB	072H
	DB	072H
	DB	04dH
	DB	073H
	DB	067H
	DB	00H
	DB	065H
	DB	072H
	DB	072H
	DB	04dH
	DB	073H
	DB	067H
	DB	00H
	DB	068H
	DB	061H
	DB	06eH
	DB	064H
	DB	06cH
	DB	065H
	DB	049H
	DB	06eH
	DB	066H
	DB	06fH
	DB	04dH
	DB	073H
	DB	067H
	DB	00H
	DB	074H
	DB	072H
	DB	069H
	DB	067H
	DB	067H
	DB	065H
	DB	072H
	DB	04eH
	DB	06fH
	DB	077H
	DB	00H
	DB	06fH
	DB	06eH
	DB	041H
	DB	06cH
	DB	06cH
	DB	054H
	DB	068H
	DB	072H
	DB	065H
	DB	061H
	DB	064H
	DB	073H
	DB	053H
	DB	074H
	DB	061H
	DB	072H
	DB	074H
	DB	065H
	DB	064H
	DB	00H
	DB	074H
	DB	069H
	DB	06dH
	DB	065H
	DB	072H
	DB	054H
	DB	069H
	DB	06dH
	DB	065H
	DB	06fH
	DB	075H
	DB	074H
	DB	00H
	DB	070H
	DB	072H
	DB	065H
	DB	073H
	DB	065H
	DB	06eH
	DB	074H
	DB	044H
	DB	061H
	DB	074H
	DB	061H
	DB	00H
	ORG $+3
?qt_meta_data_qSanityChkDlg@@3QBIB DD 08H		; qt_meta_data_qSanityChkDlg
	DD	00H
	DD	00H
	DD	00H
	DD	0aH
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	00H
	DD	040H
	DD	02H
	DD	0aH
	DD	03H
	DD	00H
	DD	041H
	DD	02H
	DD	0aH
	DD	04H
	DD	01H
	DD	042H
	DD	02H
	DD	0aH
	DD	06H
	DD	00H
	DD	045H
	DD	02H
	DD	0aH
	DD	07H
	DD	01H
	DD	046H
	DD	02H
	DD	08H
	DD	09H
	DD	01H
	DD	049H
	DD	02H
	DD	08H
	DD	0aH
	DD	00H
	DD	04cH
	DD	02H
	DD	08H
	DD	0bH
	DD	00H
	DD	04dH
	DD	02H
	DD	08H
	DD	0cH
	DD	00H
	DD	04eH
	DD	02H
	DD	08H
	DD	0dH
	DD	00H
	DD	04fH
	DD	02H
	DD	08H
	DD	02bH
	DD	02bH
	DD	02bH
	DD	01H
	DD	05H
	DD	02bH
	DD	02bH
	DD	0aH
	DD	08H
	DD	02bH
	DD	0aH
	DD	08H
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	00H
CONST	ENDS
PUBLIC	?metaObject@qSanityChkDlg@@UBEPBUQMetaObject@@XZ ; qSanityChkDlg::metaObject
PUBLIC	?qt_metacast@qSanityChkDlg@@UAEPAXPBD@Z		; qSanityChkDlg::qt_metacast
PUBLIC	?qt_metacall@qSanityChkDlg@@UAEHW4Call@QMetaObject@@HPAPAX@Z ; qSanityChkDlg::qt_metacall
PUBLIC	?qt_static_metacall@qSanityChkDlg@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z ; qSanityChkDlg::qt_static_metacall
PUBLIC	?staticMetaObject@qSanityChkDlg@@2UQMetaObject@@B ; qSanityChkDlg::staticMetaObject
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QBEPAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QDialog@@UAEPAXPBD@Z:PROC
EXTRN	__imp_?qt_metacall@QDialog@@UAEHW4Call@QMetaObject@@HPAPAX@Z:PROC
EXTRN	?onRelayOpened@qSanityChkDlg@@QAEX_N@Z:PROC	; qSanityChkDlg::onRelayOpened
EXTRN	?onTestBtnClicked@qSanityChkDlg@@QAEXXZ:PROC	; qSanityChkDlg::onTestBtnClicked
EXTRN	?handleErrMsg@qSanityChkDlg@@AAEXABVQString@@@Z:PROC ; qSanityChkDlg::handleErrMsg
EXTRN	?handleInfoMsg@qSanityChkDlg@@AAEXABVQString@@@Z:PROC ; qSanityChkDlg::handleInfoMsg
EXTRN	?triggerNow@qSanityChkDlg@@AAEXXZ:PROC		; qSanityChkDlg::triggerNow
EXTRN	?onAllThreadsStarted@qSanityChkDlg@@AAEXXZ:PROC	; qSanityChkDlg::onAllThreadsStarted
EXTRN	?timerTimeout@qSanityChkDlg@@AAEXXZ:PROC	; qSanityChkDlg::timerTimeout
EXTRN	?presentData@qSanityChkDlg@@AAEXXZ:PROC		; qSanityChkDlg::presentData
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@qSanityChkDlg@@2P6AXXZA@@3P6AXXZA DD FLAT:??__E?staticMetaObject@qSanityChkDlg@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@qSanityChkDlg@@2P6AXXZA@@3P6AXXZA
CRT$XCU	ENDS
_DATA	SEGMENT
?staticMetaObject@qSanityChkDlg@@2UQMetaObject@@B DB 4 DUP(00H) ; qSanityChkDlg::staticMetaObject
	DD	FLAT:?qt_meta_stringdata_qSanityChkDlg@@3Uqt_meta_stringdata_qSanityChkDlg_t@@B
	DD	FLAT:?qt_meta_data_qSanityChkDlg@@3QBIB
	DD	FLAT:?qt_static_metacall@qSanityChkDlg@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z
	DD	00H
	DD	00H
_DATA	ENDS
; Function compile flags: /Ogtp
;	COMDAT ??__E?staticMetaObject@qSanityChkDlg@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@qSanityChkDlg@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'qSanityChkDlg::staticMetaObject'', COMDAT
; File c:\users\unm\documents\github\cacode\src\failsafec\generatedfiles\release\moc_qsanitychkdlg.cpp
; Line 121
	mov	eax, DWORD PTR __imp_?staticMetaObject@QDialog@@2UQMetaObject@@B
	mov	DWORD PTR ?staticMetaObject@qSanityChkDlg@@2UQMetaObject@@B, eax
; Line 126
	ret	0
??__E?staticMetaObject@qSanityChkDlg@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'qSanityChkDlg::staticMetaObject''
text$di	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?qt_static_metacall@qSanityChkDlg@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z
_TEXT	SEGMENT
__o$ = 8						; size = 4
__c$ = 12						; size = 4
__id$ = 16						; size = 4
__a$ = 20						; size = 4
?qt_static_metacall@qSanityChkDlg@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z PROC ; qSanityChkDlg::qt_static_metacall, COMDAT
; File c:\users\unm\documents\github\cacode\src\failsafec\generatedfiles\release\moc_qsanitychkdlg.cpp
; Line 100
	push	ebp
	mov	ebp, esp
; Line 101
	cmp	DWORD PTR __c$[ebp], 0
	jne	SHORT $LN15@qt_static_
; Line 104
	mov	eax, DWORD PTR __id$[ebp]
	cmp	eax, 9
	ja	SHORT $LN15@qt_static_
	jmp	DWORD PTR $LN20@qt_static_[eax*4]
$LN5@qt_static_:
; Line 105
	mov	ecx, DWORD PTR __o$[ebp]
	mov	eax, DWORD PTR [ecx]
; Line 118
	pop	ebp
; Line 105
	jmp	DWORD PTR [eax+192]
$LN6@qt_static_:
; Line 106
	mov	ecx, DWORD PTR __o$[ebp]
	mov	eax, DWORD PTR [ecx]
; Line 118
	pop	ebp
; Line 106
	jmp	DWORD PTR [eax+196]
$LN7@qt_static_:
; Line 107
	mov	eax, DWORD PTR __a$[ebp]
	mov	ecx, DWORD PTR __o$[ebp]
	mov	eax, DWORD PTR [eax+4]
	movzx	eax, BYTE PTR [eax]
	push	eax
	call	?onRelayOpened@qSanityChkDlg@@QAEX_N@Z	; qSanityChkDlg::onRelayOpened
$LN15@qt_static_:
; Line 118
	pop	ebp
	ret	0
$LN8@qt_static_:
; Line 108
	mov	ecx, DWORD PTR __o$[ebp]
; Line 118
	pop	ebp
; Line 108
	jmp	?onTestBtnClicked@qSanityChkDlg@@QAEXXZ	; qSanityChkDlg::onTestBtnClicked
$LN9@qt_static_:
; Line 109
	mov	eax, DWORD PTR __a$[ebp]
	mov	ecx, DWORD PTR __o$[ebp]
	push	DWORD PTR [eax+4]
	call	?handleErrMsg@qSanityChkDlg@@AAEXABVQString@@@Z ; qSanityChkDlg::handleErrMsg
; Line 118
	pop	ebp
	ret	0
$LN10@qt_static_:
; Line 110
	mov	eax, DWORD PTR __a$[ebp]
	mov	ecx, DWORD PTR __o$[ebp]
	push	DWORD PTR [eax+4]
	call	?handleInfoMsg@qSanityChkDlg@@AAEXABVQString@@@Z ; qSanityChkDlg::handleInfoMsg
; Line 118
	pop	ebp
	ret	0
$LN11@qt_static_:
; Line 111
	mov	ecx, DWORD PTR __o$[ebp]
; Line 118
	pop	ebp
; Line 111
	jmp	?triggerNow@qSanityChkDlg@@AAEXXZ	; qSanityChkDlg::triggerNow
$LN12@qt_static_:
; Line 112
	mov	ecx, DWORD PTR __o$[ebp]
; Line 118
	pop	ebp
; Line 112
	jmp	?onAllThreadsStarted@qSanityChkDlg@@AAEXXZ ; qSanityChkDlg::onAllThreadsStarted
$LN13@qt_static_:
; Line 113
	mov	ecx, DWORD PTR __o$[ebp]
; Line 118
	pop	ebp
; Line 113
	jmp	?timerTimeout@qSanityChkDlg@@AAEXXZ	; qSanityChkDlg::timerTimeout
$LN14@qt_static_:
; Line 114
	mov	ecx, DWORD PTR __o$[ebp]
; Line 118
	pop	ebp
; Line 114
	jmp	?presentData@qSanityChkDlg@@AAEXXZ	; qSanityChkDlg::presentData
	npad	3
$LN20@qt_static_:
; Line 118
	DD	$LN5@qt_static_
	DD	$LN6@qt_static_
	DD	$LN7@qt_static_
	DD	$LN8@qt_static_
	DD	$LN9@qt_static_
	DD	$LN10@qt_static_
	DD	$LN11@qt_static_
	DD	$LN12@qt_static_
	DD	$LN13@qt_static_
	DD	$LN14@qt_static_
?qt_static_metacall@qSanityChkDlg@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z ENDP ; qSanityChkDlg::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?qt_metacall@qSanityChkDlg@@UAEHW4Call@QMetaObject@@HPAPAX@Z
_TEXT	SEGMENT
_this$1$ = -4						; size = 4
__c$ = 8						; size = 4
__id$ = 12						; size = 4
__a$ = 16						; size = 4
?qt_metacall@qSanityChkDlg@@UAEHW4Call@QMetaObject@@HPAPAX@Z PROC ; qSanityChkDlg::qt_metacall, COMDAT
; _this$ = ecx
; File c:\users\unm\documents\github\cacode\src\failsafec\generatedfiles\release\moc_qsanitychkdlg.cpp
; Line 144
	push	ebp
	mov	ebp, esp
	push	ecx
	push	ebx
; Line 145
	mov	ebx, DWORD PTR __a$[ebp]
	mov	eax, ecx
	push	esi
	push	edi
	mov	edi, DWORD PTR __c$[ebp]
	push	ebx
	push	DWORD PTR __id$[ebp]
	mov	DWORD PTR _this$1$[ebp], eax
	push	edi
	call	DWORD PTR __imp_?qt_metacall@QDialog@@UAEHW4Call@QMetaObject@@HPAPAX@Z
	mov	esi, eax
; Line 146
	test	esi, esi
	js	SHORT $LN1@qt_metacal
; Line 148
	test	edi, edi
	jne	SHORT $LN3@qt_metacal
; Line 149
	cmp	esi, 10					; 0000000aH
	jge	SHORT $LN7@qt_metacal
; Line 150
	push	ebx
	push	esi
	push	edi
	push	DWORD PTR _this$1$[ebp]
	call	?qt_static_metacall@qSanityChkDlg@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z ; qSanityChkDlg::qt_static_metacall
	add	esp, 16					; 00000010H
; Line 157
	sub	esi, 10					; 0000000aH
	mov	eax, esi
	pop	edi
; Line 158
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
$LN3@qt_metacal:
; Line 152
	cmp	edi, 12					; 0000000cH
	jne	SHORT $LN6@qt_metacal
; Line 153
	cmp	esi, 10					; 0000000aH
	jge	SHORT $LN7@qt_metacal
; Line 154
	mov	eax, DWORD PTR [ebx]
	mov	DWORD PTR [eax], -1
$LN7@qt_metacal:
; Line 157
	sub	esi, 10					; 0000000aH
$LN6@qt_metacal:
	mov	eax, esi
$LN1@qt_metacal:
	pop	edi
; Line 158
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
?qt_metacall@qSanityChkDlg@@UAEHW4Call@QMetaObject@@HPAPAX@Z ENDP ; qSanityChkDlg::qt_metacall
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?qt_metacast@qSanityChkDlg@@UAEPAXPBD@Z
_TEXT	SEGMENT
__clname$ = 8						; size = 4
?qt_metacast@qSanityChkDlg@@UAEPAXPBD@Z PROC		; qSanityChkDlg::qt_metacast, COMDAT
; _this$ = ecx
; File c:\users\unm\documents\github\cacode\src\failsafec\generatedfiles\release\moc_qsanitychkdlg.cpp
; Line 136
	push	ebp
	mov	ebp, esp
	push	esi
; Line 137
	mov	esi, DWORD PTR __clname$[ebp]
	push	edi
	mov	edi, ecx
	test	esi, esi
	jne	SHORT $LN2@qt_metacas
	pop	edi
	xor	eax, eax
; Line 141
	pop	esi
	pop	ebp
	ret	4
$LN2@qt_metacas:
; Line 138
	mov	eax, OFFSET ?qt_meta_stringdata_qSanityChkDlg@@3Uqt_meta_stringdata_qSanityChkDlg_t@@B+224
	mov	ecx, esi
	npad	3
$LL5@qt_metacas:
	mov	dl, BYTE PTR [ecx]
	cmp	dl, BYTE PTR [eax]
	jne	SHORT $LN6@qt_metacas
	test	dl, dl
	je	SHORT $LN7@qt_metacas
	mov	dl, BYTE PTR [ecx+1]
	cmp	dl, BYTE PTR [eax+1]
	jne	SHORT $LN6@qt_metacas
	add	ecx, 2
	add	eax, 2
	test	dl, dl
	jne	SHORT $LL5@qt_metacas
$LN7@qt_metacas:
	xor	eax, eax
	jmp	SHORT $LN8@qt_metacas
$LN6@qt_metacas:
	sbb	eax, eax
	or	eax, 1
$LN8@qt_metacas:
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 139
	mov	eax, edi
	pop	edi
; Line 141
	pop	esi
	pop	ebp
	ret	4
$LN3@qt_metacas:
; Line 140
	push	esi
	mov	ecx, edi
	call	DWORD PTR __imp_?qt_metacast@QDialog@@UAEPAXPBD@Z
	pop	edi
; Line 141
	pop	esi
	pop	ebp
	ret	4
?qt_metacast@qSanityChkDlg@@UAEPAXPBD@Z ENDP		; qSanityChkDlg::qt_metacast
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?metaObject@qSanityChkDlg@@UBEPBUQMetaObject@@XZ
_TEXT	SEGMENT
?metaObject@qSanityChkDlg@@UBEPBUQMetaObject@@XZ PROC	; qSanityChkDlg::metaObject, COMDAT
; _this$ = ecx
; File c:\users\unm\documents\github\cacode\src\failsafec\generatedfiles\release\moc_qsanitychkdlg.cpp
; Line 132
	mov	ecx, DWORD PTR [ecx+4]
	cmp	DWORD PTR [ecx+24], 0
	je	SHORT $LN3@metaObject
	jmp	DWORD PTR __imp_?dynamicMetaObject@QObjectData@@QBEPAUQMetaObject@@XZ
$LN3@metaObject:
	mov	eax, OFFSET ?staticMetaObject@qSanityChkDlg@@2UQMetaObject@@B ; qSanityChkDlg::staticMetaObject
; Line 133
	ret	0
?metaObject@qSanityChkDlg@@UBEPBUQMetaObject@@XZ ENDP	; qSanityChkDlg::metaObject
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ
_TEXT	SEGMENT
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; _this$ = ecx
; File c:\qt\5.13.1\msvc2017\include\qtcore\qscopedpointer.h
; Line 118
	mov	eax, DWORD PTR [ecx]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
END
