; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27032.1 

	TITLE	C:\Users\unm\Documents\GitHub\caCode\src\failSafeC\GeneratedFiles\Release\moc_qManualCheckPage.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

EXTRN	__imp_?staticMetaObject@QWizardPage@@2UQMetaObject@@B:BYTE
CONST	SEGMENT
?qt_meta_stringdata_qManualCheckPage@@3Uqt_meta_stringdata_qManualCheckPage_t@@B DD 0ffffffffH ; qt_meta_stringdata_qManualCheckPage
	DD	010H
	DD	00H
	DD	010H
	DB	071H
	DB	04dH
	DB	061H
	DB	06eH
	DB	075H
	DB	061H
	DB	06cH
	DB	043H
	DB	068H
	DB	065H
	DB	063H
	DB	06bH
	DB	050H
	DB	061H
	DB	067H
	DB	065H
	DB	00H
	ORG $+3
?qt_meta_data_qManualCheckPage@@3QBIB DD 08H		; qt_meta_data_qManualCheckPage
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
CONST	ENDS
PUBLIC	?metaObject@qManualCheckPage@@UBEPBUQMetaObject@@XZ ; qManualCheckPage::metaObject
PUBLIC	?qt_metacast@qManualCheckPage@@UAEPAXPBD@Z	; qManualCheckPage::qt_metacast
PUBLIC	?qt_metacall@qManualCheckPage@@UAEHW4Call@QMetaObject@@HPAPAX@Z ; qManualCheckPage::qt_metacall
PUBLIC	?qt_static_metacall@qManualCheckPage@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z ; qManualCheckPage::qt_static_metacall
PUBLIC	?staticMetaObject@qManualCheckPage@@2UQMetaObject@@B ; qManualCheckPage::staticMetaObject
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QBEPAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QWizardPage@@UAEPAXPBD@Z:PROC
EXTRN	__imp_?qt_metacall@QWizardPage@@UAEHW4Call@QMetaObject@@HPAPAX@Z:PROC
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@qManualCheckPage@@2P6AXXZA@@3P6AXXZA DD FLAT:??__E?staticMetaObject@qManualCheckPage@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@qManualCheckPage@@2P6AXXZA@@3P6AXXZA
CRT$XCU	ENDS
_DATA	SEGMENT
?staticMetaObject@qManualCheckPage@@2UQMetaObject@@B DB 4 DUP(00H) ; qManualCheckPage::staticMetaObject
	DD	FLAT:?qt_meta_stringdata_qManualCheckPage@@3Uqt_meta_stringdata_qManualCheckPage_t@@B
	DD	FLAT:?qt_meta_data_qManualCheckPage@@3QBIB
	DD	FLAT:?qt_static_metacall@qManualCheckPage@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z
	DD	00H
	DD	00H
_DATA	ENDS
; Function compile flags: /Ogtp
;	COMDAT ??__E?staticMetaObject@qManualCheckPage@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@qManualCheckPage@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'qManualCheckPage::staticMetaObject'', COMDAT
; File c:\users\unm\documents\github\cacode\src\failsafec\generatedfiles\release\moc_qmanualcheckpage.cpp
; Line 67
	mov	eax, DWORD PTR __imp_?staticMetaObject@QWizardPage@@2UQMetaObject@@B
	mov	DWORD PTR ?staticMetaObject@qManualCheckPage@@2UQMetaObject@@B, eax
; Line 72
	ret	0
??__E?staticMetaObject@qManualCheckPage@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'qManualCheckPage::staticMetaObject''
text$di	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?qt_static_metacall@qManualCheckPage@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z
_TEXT	SEGMENT
__o$ = 8						; size = 4
__c$ = 12						; size = 4
__id$ = 16						; size = 4
__a$ = 20						; size = 4
?qt_static_metacall@qManualCheckPage@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z PROC ; qManualCheckPage::qt_static_metacall, COMDAT
; File c:\users\unm\documents\github\cacode\src\failsafec\generatedfiles\release\moc_qmanualcheckpage.cpp
; Line 64
	ret	0
?qt_static_metacall@qManualCheckPage@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z ENDP ; qManualCheckPage::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?qt_metacall@qManualCheckPage@@UAEHW4Call@QMetaObject@@HPAPAX@Z
_TEXT	SEGMENT
__c$ = 8						; size = 4
__id$ = 12						; size = 4
__a$ = 16						; size = 4
?qt_metacall@qManualCheckPage@@UAEHW4Call@QMetaObject@@HPAPAX@Z PROC ; qManualCheckPage::qt_metacall, COMDAT
; _this$ = ecx
; File c:\users\unm\documents\github\cacode\src\failsafec\generatedfiles\release\moc_qmanualcheckpage.cpp
; Line 90
	push	ebp
	mov	ebp, esp
; Line 93
	pop	ebp
; Line 91
	jmp	DWORD PTR __imp_?qt_metacall@QWizardPage@@UAEHW4Call@QMetaObject@@HPAPAX@Z
?qt_metacall@qManualCheckPage@@UAEHW4Call@QMetaObject@@HPAPAX@Z ENDP ; qManualCheckPage::qt_metacall
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?qt_metacast@qManualCheckPage@@UAEPAXPBD@Z
_TEXT	SEGMENT
__clname$ = 8						; size = 4
?qt_metacast@qManualCheckPage@@UAEPAXPBD@Z PROC		; qManualCheckPage::qt_metacast, COMDAT
; _this$ = ecx
; File c:\users\unm\documents\github\cacode\src\failsafec\generatedfiles\release\moc_qmanualcheckpage.cpp
; Line 82
	push	ebp
	mov	ebp, esp
	push	esi
; Line 83
	mov	esi, DWORD PTR __clname$[ebp]
	push	edi
	mov	edi, ecx
	test	esi, esi
	jne	SHORT $LN2@qt_metacas
	pop	edi
	xor	eax, eax
; Line 87
	pop	esi
	pop	ebp
	ret	4
$LN2@qt_metacas:
; Line 84
	mov	eax, OFFSET ?qt_meta_stringdata_qManualCheckPage@@3Uqt_meta_stringdata_qManualCheckPage_t@@B+16
	mov	ecx, esi
	npad	3
$LL5@qt_metacas:
	mov	dl, BYTE PTR [ecx]
	cmp	dl, BYTE PTR [eax]
	jne	SHORT $LN6@qt_metacas
	test	dl, dl
	je	SHORT $LN7@qt_metacas
	mov	dl, BYTE PTR [ecx+1]
	cmp	dl, BYTE PTR [eax+1]
	jne	SHORT $LN6@qt_metacas
	add	ecx, 2
	add	eax, 2
	test	dl, dl
	jne	SHORT $LL5@qt_metacas
$LN7@qt_metacas:
	xor	eax, eax
	jmp	SHORT $LN8@qt_metacas
$LN6@qt_metacas:
	sbb	eax, eax
	or	eax, 1
$LN8@qt_metacas:
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 85
	mov	eax, edi
	pop	edi
; Line 87
	pop	esi
	pop	ebp
	ret	4
$LN3@qt_metacas:
; Line 86
	push	esi
	mov	ecx, edi
	call	DWORD PTR __imp_?qt_metacast@QWizardPage@@UAEPAXPBD@Z
	pop	edi
; Line 87
	pop	esi
	pop	ebp
	ret	4
?qt_metacast@qManualCheckPage@@UAEPAXPBD@Z ENDP		; qManualCheckPage::qt_metacast
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?metaObject@qManualCheckPage@@UBEPBUQMetaObject@@XZ
_TEXT	SEGMENT
?metaObject@qManualCheckPage@@UBEPBUQMetaObject@@XZ PROC ; qManualCheckPage::metaObject, COMDAT
; _this$ = ecx
; File c:\users\unm\documents\github\cacode\src\failsafec\generatedfiles\release\moc_qmanualcheckpage.cpp
; Line 78
	mov	ecx, DWORD PTR [ecx+4]
	cmp	DWORD PTR [ecx+24], 0
	je	SHORT $LN3@metaObject
	jmp	DWORD PTR __imp_?dynamicMetaObject@QObjectData@@QBEPAUQMetaObject@@XZ
$LN3@metaObject:
	mov	eax, OFFSET ?staticMetaObject@qManualCheckPage@@2UQMetaObject@@B ; qManualCheckPage::staticMetaObject
; Line 79
	ret	0
?metaObject@qManualCheckPage@@UBEPBUQMetaObject@@XZ ENDP ; qManualCheckPage::metaObject
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ
_TEXT	SEGMENT
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; _this$ = ecx
; File c:\qt\5.13.1\msvc2017\include\qtcore\qscopedpointer.h
; Line 118
	mov	eax, DWORD PTR [ecx]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
END
