; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27032.1 

	TITLE	C:\Users\unm\Documents\GitHub\caCode\src\sendWaveformC\Release\moc\moc_keysight33503A.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

EXTRN	__imp_?staticMetaObject@QThread@@2UQMetaObject@@B:BYTE
CONST	SEGMENT
?qt_meta_stringdata_keysight33503A@@3Uqt_meta_stringdata_keysight33503A_t@@B DD 0ffffffffH ; qt_meta_stringdata_keysight33503A
	DD	0eH
	DD	00H
	DD	040H
	DD	0ffffffffH
	DD	06H
	DD	00H
	DD	03fH
	DD	0ffffffffH
	DD	00H
	DD	00H
	DD	036H
	DD	0ffffffffH
	DD	03H
	DD	00H
	DD	027H
	DB	06bH
	DB	065H
	DB	079H
	DB	073H
	DB	069H
	DB	067H
	DB	068H
	DB	074H
	DB	033H
	DB	033H
	DB	035H
	DB	030H
	DB	033H
	DB	041H
	DB	00H
	DB	065H
	DB	072H
	DB	072H
	DB	04dH
	DB	073H
	DB	067H
	DB	00H
	DB	00H
	DB	06dH
	DB	073H
	DB	067H
	DB	00H
	ORG $+1
	ORG $+4
?qt_meta_data_keysight33503A@@3QBIB DD 08H		; qt_meta_data_keysight33503A
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	01H
	DD	01H
	DD	013H
	DD	02H
	DD	06H
	DD	02bH
	DD	0aH
	DD	03H
	DD	00H
CONST	ENDS
PUBLIC	?metaObject@keysight33503A@@UBEPBUQMetaObject@@XZ ; keysight33503A::metaObject
PUBLIC	?qt_metacast@keysight33503A@@UAEPAXPBD@Z	; keysight33503A::qt_metacast
PUBLIC	?qt_metacall@keysight33503A@@UAEHW4Call@QMetaObject@@HPAPAX@Z ; keysight33503A::qt_metacall
PUBLIC	?qt_static_metacall@keysight33503A@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z ; keysight33503A::qt_static_metacall
PUBLIC	?errMsg@keysight33503A@@QAEXVQString@@@Z	; keysight33503A::errMsg
PUBLIC	?staticMetaObject@keysight33503A@@2UQMetaObject@@B ; keysight33503A::staticMetaObject
EXTRN	__imp_?activate@QMetaObject@@SAXPAVQObject@@PBU1@HPAPAX@Z:PROC
EXTRN	__imp_??0QString@@QAE@ABV0@@Z:PROC
EXTRN	__imp_??1QString@@QAE@XZ:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QBEPAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QThread@@UAEPAXPBD@Z:PROC
EXTRN	__imp_?qt_metacall@QThread@@UAEHW4Call@QMetaObject@@HPAPAX@Z:PROC
EXTRN	@__security_check_cookie@4:PROC
EXTRN	___CxxFrameHandler3:PROC
EXTRN	___security_cookie:DWORD
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@keysight33503A@@2P6AXXZA@@3P6AXXZA DD FLAT:??__E?staticMetaObject@keysight33503A@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@keysight33503A@@2P6AXXZA@@3P6AXXZA
CRT$XCU	ENDS
_DATA	SEGMENT
?staticMetaObject@keysight33503A@@2UQMetaObject@@B DB 4 DUP(00H) ; keysight33503A::staticMetaObject
	DD	FLAT:?qt_meta_stringdata_keysight33503A@@3Uqt_meta_stringdata_keysight33503A_t@@B
	DD	FLAT:?qt_meta_data_keysight33503A@@3QBIB
	DD	FLAT:?qt_static_metacall@keysight33503A@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z
	DD	00H
	DD	00H
_DATA	ENDS
;	COMDAT xdata$x
xdata$x	SEGMENT
__unwindtable$?errMsg@keysight33503A@@QAEXVQString@@@Z DD 0ffffffffH
	DD	FLAT:__unwindfunclet$?errMsg@keysight33503A@@QAEXVQString@@@Z$0
__ehfuncinfo$?errMsg@keysight33503A@@QAEXVQString@@@Z DD 019930522H
	DD	01H
	DD	FLAT:__unwindtable$?errMsg@keysight33503A@@QAEXVQString@@@Z
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	DD	00H
	DD	01H
xdata$x	ENDS
;	COMDAT xdata$x
xdata$x	SEGMENT
__unwindtable$?qt_static_metacall@keysight33503A@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z DD 0ffffffffH
	DD	FLAT:__unwindfunclet$?qt_static_metacall@keysight33503A@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z$1
__ehfuncinfo$?qt_static_metacall@keysight33503A@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z DD 019930522H
	DD	01H
	DD	FLAT:__unwindtable$?qt_static_metacall@keysight33503A@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	DD	00H
	DD	01H
xdata$x	ENDS
; Function compile flags: /Ogtp
;	COMDAT ??$addressof@VQString@@@std@@YAPAVQString@@AAV1@@Z
_TEXT	SEGMENT
__Val$ = 8						; size = 4
??$addressof@VQString@@@std@@YAPAVQString@@AAV1@@Z PROC	; std::addressof<QString>, COMDAT
; File c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\xstddef
; Line 329
	push	ebp
	mov	ebp, esp
; Line 330
	mov	eax, DWORD PTR __Val$[ebp]
; Line 331
	pop	ebp
	ret	0
??$addressof@VQString@@@std@@YAPAVQString@@AAV1@@Z ENDP	; std::addressof<QString>
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ??__E?staticMetaObject@keysight33503A@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@keysight33503A@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'keysight33503A::staticMetaObject'', COMDAT
; File c:\users\unm\documents\github\cacode\src\sendwaveformc\release\moc\moc_keysight33503a.cpp
; Line 89
	mov	eax, DWORD PTR __imp_?staticMetaObject@QThread@@2UQMetaObject@@B
	mov	DWORD PTR ?staticMetaObject@keysight33503A@@2UQMetaObject@@B, eax
; Line 94
	ret	0
??__E?staticMetaObject@keysight33503A@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'keysight33503A::staticMetaObject''
text$di	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?errMsg@keysight33503A@@QAEXVQString@@@Z
_TEXT	SEGMENT
__a$ = -20						; size = 8
__$EHRec$ = -12						; size = 12
__t1$ = 8						; size = 4
?errMsg@keysight33503A@@QAEXVQString@@@Z PROC		; keysight33503A::errMsg, COMDAT
; _this$ = ecx
; File c:\users\unm\documents\github\cacode\src\sendwaveformc\release\moc\moc_keysight33503a.cpp
; Line 130
	push	ebp
	mov	ebp, esp
	push	-1
	push	__ehhandler$?errMsg@keysight33503A@@QAEXVQString@@@Z
	mov	eax, DWORD PTR fs:0
	push	eax
	sub	esp, 8
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	push	eax
	lea	eax, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, eax
; File c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\xstddef
; Line 330
	lea	eax, DWORD PTR __t1$[ebp]
; File c:\users\unm\documents\github\cacode\src\sendwaveformc\release\moc\moc_keysight33503a.cpp
; Line 130
	mov	DWORD PTR __$EHRec$[ebp+8], 0
; File c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\xstddef
; Line 330
	mov	DWORD PTR __a$[ebp+4], eax
; File c:\users\unm\documents\github\cacode\src\sendwaveformc\release\moc\moc_keysight33503a.cpp
; Line 132
	lea	eax, DWORD PTR __a$[ebp]
	push	eax
	push	0
	push	OFFSET ?staticMetaObject@keysight33503A@@2UQMetaObject@@B ; keysight33503A::staticMetaObject
	push	ecx
	mov	DWORD PTR __a$[ebp], 0
	call	DWORD PTR __imp_?activate@QMetaObject@@SAXPAVQObject@@PBU1@HPAPAX@Z
	add	esp, 16					; 00000010H
; Line 133
	lea	ecx, DWORD PTR __t1$[ebp]
	call	DWORD PTR __imp_??1QString@@QAE@XZ
	mov	ecx, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, ecx
	pop	ecx
	mov	esp, ebp
	pop	ebp
	ret	4
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
__unwindfunclet$?errMsg@keysight33503A@@QAEXVQString@@@Z$0:
	lea	ecx, DWORD PTR __t1$[ebp]
	jmp	DWORD PTR __imp_??1QString@@QAE@XZ
__ehhandler$?errMsg@keysight33503A@@QAEXVQString@@@Z:
	mov	edx, DWORD PTR [esp+8]
	lea	eax, DWORD PTR [edx+12]
	mov	ecx, DWORD PTR [edx-12]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	eax, OFFSET __ehfuncinfo$?errMsg@keysight33503A@@QAEXVQString@@@Z
	jmp	___CxxFrameHandler3
text$x	ENDS
?errMsg@keysight33503A@@QAEXVQString@@@Z ENDP		; keysight33503A::errMsg
; Function compile flags: /Ogtp
;	COMDAT ?qt_static_metacall@keysight33503A@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z
_TEXT	SEGMENT
__a$2 = -20						; size = 8
__$EHRec$ = -12						; size = 12
__o$ = 8						; size = 4
$T3 = 12						; size = 4
__c$ = 12						; size = 4
__id$ = 16						; size = 4
__a$ = 20						; size = 4
?qt_static_metacall@keysight33503A@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z PROC ; keysight33503A::qt_static_metacall, COMDAT
; File c:\users\unm\documents\github\cacode\src\sendwaveformc\release\moc\moc_keysight33503a.cpp
; Line 68
	push	ebp
	mov	ebp, esp
	push	-1
	push	__ehhandler$?qt_static_metacall@keysight33503A@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z
	mov	eax, DWORD PTR fs:0
	push	eax
	sub	esp, 8
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	push	eax
	lea	eax, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, eax
; Line 69
	mov	eax, DWORD PTR __c$[ebp]
	test	eax, eax
	jne	SHORT $LN4@qt_static_
; Line 72
	cmp	DWORD PTR __id$[ebp], eax
	jne	SHORT $LN9@qt_static_
; Line 73
	mov	eax, DWORD PTR __a$[ebp]
	lea	ecx, DWORD PTR $T3[ebp]
	push	DWORD PTR [eax+4]
	call	DWORD PTR __imp_??0QString@@QAE@ABV0@@Z
; File c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\xstddef
; Line 330
	lea	eax, DWORD PTR $T3[ebp]
; File c:\users\unm\documents\github\cacode\src\sendwaveformc\release\moc\moc_keysight33503a.cpp
; Line 130
	mov	DWORD PTR __$EHRec$[ebp+8], 0
; File c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\xstddef
; Line 330
	mov	DWORD PTR __a$2[ebp+4], eax
; File c:\users\unm\documents\github\cacode\src\sendwaveformc\release\moc\moc_keysight33503a.cpp
; Line 132
	lea	eax, DWORD PTR __a$2[ebp]
	push	eax
	push	0
	push	OFFSET ?staticMetaObject@keysight33503A@@2UQMetaObject@@B ; keysight33503A::staticMetaObject
	push	DWORD PTR __o$[ebp]
	mov	DWORD PTR __a$2[ebp], 0
	call	DWORD PTR __imp_?activate@QMetaObject@@SAXPAVQObject@@PBU1@HPAPAX@Z
	add	esp, 16					; 00000010H
; Line 133
	lea	ecx, DWORD PTR $T3[ebp]
	call	DWORD PTR __imp_??1QString@@QAE@XZ
; Line 86
	mov	ecx, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, ecx
	pop	ecx
	mov	esp, ebp
	pop	ebp
	ret	0
$LN4@qt_static_:
; Line 76
	cmp	eax, 10					; 0000000aH
	jne	SHORT $LN9@qt_static_
; Line 80
	mov	ecx, DWORD PTR __a$[ebp]
	mov	eax, DWORD PTR [ecx+4]
	cmp	DWORD PTR [eax], OFFSET ?errMsg@keysight33503A@@QAEXVQString@@@Z ; keysight33503A::errMsg
	jne	SHORT $LN9@qt_static_
; Line 81
	mov	eax, DWORD PTR [ecx]
	mov	DWORD PTR [eax], 0
$LN9@qt_static_:
; Line 86
	mov	ecx, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, ecx
	pop	ecx
	mov	esp, ebp
	pop	ebp
	ret	0
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
__unwindfunclet$?qt_static_metacall@keysight33503A@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z$1:
	lea	ecx, DWORD PTR $T3[ebp]
	jmp	DWORD PTR __imp_??1QString@@QAE@XZ
__ehhandler$?qt_static_metacall@keysight33503A@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z:
	mov	edx, DWORD PTR [esp+8]
	lea	eax, DWORD PTR [edx+12]
	mov	ecx, DWORD PTR [edx-12]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	eax, OFFSET __ehfuncinfo$?qt_static_metacall@keysight33503A@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z
	jmp	___CxxFrameHandler3
text$x	ENDS
?qt_static_metacall@keysight33503A@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z ENDP ; keysight33503A::qt_static_metacall
; Function compile flags: /Ogtp
;	COMDAT ?qt_metacall@keysight33503A@@UAEHW4Call@QMetaObject@@HPAPAX@Z
_TEXT	SEGMENT
_this$1$ = -4						; size = 4
__c$ = 8						; size = 4
__id$ = 12						; size = 4
__a$ = 16						; size = 4
?qt_metacall@keysight33503A@@UAEHW4Call@QMetaObject@@HPAPAX@Z PROC ; keysight33503A::qt_metacall, COMDAT
; _this$ = ecx
; File c:\users\unm\documents\github\cacode\src\sendwaveformc\release\moc\moc_keysight33503a.cpp
; Line 112
	push	ebp
	mov	ebp, esp
	push	ecx
	push	ebx
; Line 113
	mov	ebx, DWORD PTR __a$[ebp]
	mov	eax, ecx
	push	esi
	push	edi
	mov	edi, DWORD PTR __c$[ebp]
	push	ebx
	push	DWORD PTR __id$[ebp]
	mov	DWORD PTR _this$1$[ebp], eax
	push	edi
	call	DWORD PTR __imp_?qt_metacall@QThread@@UAEHW4Call@QMetaObject@@HPAPAX@Z
	mov	esi, eax
; Line 114
	test	esi, esi
	js	SHORT $LN1@qt_metacal
; Line 116
	test	edi, edi
	jne	SHORT $LN3@qt_metacal
; Line 117
	cmp	esi, 1
	jge	SHORT $LN7@qt_metacal
; Line 118
	push	ebx
	push	esi
	push	edi
	push	DWORD PTR _this$1$[ebp]
	call	?qt_static_metacall@keysight33503A@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z ; keysight33503A::qt_static_metacall
	add	esp, 16					; 00000010H
; Line 125
	dec	esi
	mov	eax, esi
	pop	edi
; Line 126
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
$LN3@qt_metacal:
; Line 120
	cmp	edi, 12					; 0000000cH
	jne	SHORT $LN6@qt_metacal
; Line 121
	cmp	esi, 1
	jge	SHORT $LN7@qt_metacal
; Line 122
	mov	eax, DWORD PTR [ebx]
	mov	DWORD PTR [eax], -1
$LN7@qt_metacal:
; Line 125
	dec	esi
$LN6@qt_metacal:
	mov	eax, esi
$LN1@qt_metacal:
	pop	edi
; Line 126
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
?qt_metacall@keysight33503A@@UAEHW4Call@QMetaObject@@HPAPAX@Z ENDP ; keysight33503A::qt_metacall
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?qt_metacast@keysight33503A@@UAEPAXPBD@Z
_TEXT	SEGMENT
__clname$ = 8						; size = 4
?qt_metacast@keysight33503A@@UAEPAXPBD@Z PROC		; keysight33503A::qt_metacast, COMDAT
; _this$ = ecx
; File c:\users\unm\documents\github\cacode\src\sendwaveformc\release\moc\moc_keysight33503a.cpp
; Line 104
	push	ebp
	mov	ebp, esp
	push	esi
; Line 105
	mov	esi, DWORD PTR __clname$[ebp]
	push	edi
	mov	edi, ecx
	test	esi, esi
	jne	SHORT $LN2@qt_metacas
	pop	edi
	xor	eax, eax
; Line 109
	pop	esi
	pop	ebp
	ret	4
$LN2@qt_metacas:
; Line 106
	mov	eax, OFFSET ?qt_meta_stringdata_keysight33503A@@3Uqt_meta_stringdata_keysight33503A_t@@B+64
	mov	ecx, esi
	npad	3
$LL5@qt_metacas:
	mov	dl, BYTE PTR [ecx]
	cmp	dl, BYTE PTR [eax]
	jne	SHORT $LN6@qt_metacas
	test	dl, dl
	je	SHORT $LN7@qt_metacas
	mov	dl, BYTE PTR [ecx+1]
	cmp	dl, BYTE PTR [eax+1]
	jne	SHORT $LN6@qt_metacas
	add	ecx, 2
	add	eax, 2
	test	dl, dl
	jne	SHORT $LL5@qt_metacas
$LN7@qt_metacas:
	xor	eax, eax
	jmp	SHORT $LN8@qt_metacas
$LN6@qt_metacas:
	sbb	eax, eax
	or	eax, 1
$LN8@qt_metacas:
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 107
	mov	eax, edi
	pop	edi
; Line 109
	pop	esi
	pop	ebp
	ret	4
$LN3@qt_metacas:
; Line 108
	push	esi
	mov	ecx, edi
	call	DWORD PTR __imp_?qt_metacast@QThread@@UAEPAXPBD@Z
	pop	edi
; Line 109
	pop	esi
	pop	ebp
	ret	4
?qt_metacast@keysight33503A@@UAEPAXPBD@Z ENDP		; keysight33503A::qt_metacast
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?metaObject@keysight33503A@@UBEPBUQMetaObject@@XZ
_TEXT	SEGMENT
?metaObject@keysight33503A@@UBEPBUQMetaObject@@XZ PROC	; keysight33503A::metaObject, COMDAT
; _this$ = ecx
; File c:\users\unm\documents\github\cacode\src\sendwaveformc\release\moc\moc_keysight33503a.cpp
; Line 100
	mov	ecx, DWORD PTR [ecx+4]
	cmp	DWORD PTR [ecx+24], 0
	je	SHORT $LN3@metaObject
	jmp	DWORD PTR __imp_?dynamicMetaObject@QObjectData@@QBEPAUQMetaObject@@XZ
$LN3@metaObject:
	mov	eax, OFFSET ?staticMetaObject@keysight33503A@@2UQMetaObject@@B ; keysight33503A::staticMetaObject
; Line 101
	ret	0
?metaObject@keysight33503A@@UBEPBUQMetaObject@@XZ ENDP	; keysight33503A::metaObject
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ
_TEXT	SEGMENT
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; _this$ = ecx
; File c:\qt\5.13.1\msvc2017\include\qtcore\qscopedpointer.h
; Line 118
	mov	eax, DWORD PTR [ecx]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
END
