; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27032.1 

	TITLE	C:\Users\unm\Documents\GitHub\caCode\src\sendWaveformC\Release\rcc\qrc_sendWaveformC.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	?qInitResources_sendWaveformC@@YAHXZ		; qInitResources_sendWaveformC
PUBLIC	?qCleanupResources_sendWaveformC@@YAHXZ		; qCleanupResources_sendWaveformC
PUBLIC	?dummy@?A0xf28512a0@@3Uinitializer@1@A		; `anonymous namespace'::dummy
EXTRN	_atexit:PROC
_BSS	SEGMENT
?dummy@?A0xf28512a0@@3Uinitializer@1@A DB 01H DUP (?)	; `anonymous namespace'::dummy
_BSS	ENDS
CRT$XCU	SEGMENT
?dummy$initializer$@?A0xf28512a0@@3P6AXXZA DD FLAT:??__Edummy@?A0xf28512a0@@YAXXZ ; `anonymous namespace'::dummy$initializer$
CRT$XCU	ENDS
; Function compile flags: /Ogtp
;	COMDAT ??__Fdummy@?A0xf28512a0@@YAXXZ
text$yd	SEGMENT
??__Fdummy@?A0xf28512a0@@YAXXZ PROC			; `anonymous namespace'::`dynamic atexit destructor for 'dummy'', COMDAT
	ret	0
??__Fdummy@?A0xf28512a0@@YAXXZ ENDP			; `anonymous namespace'::`dynamic atexit destructor for 'dummy''
text$yd	ENDS
; Function compile flags: /Ogtp
;	COMDAT ??__Edummy@?A0xf28512a0@@YAXXZ
text$di	SEGMENT
??__Edummy@?A0xf28512a0@@YAXXZ PROC			; `anonymous namespace'::`dynamic initializer for 'dummy'', COMDAT
; File c:\users\unm\documents\github\cacode\src\sendwaveformc\release\rcc\qrc_sendwaveformc.cpp
; Line 45
	push	OFFSET ??__Fdummy@?A0xf28512a0@@YAXXZ	; `anonymous namespace'::`dynamic atexit destructor for 'dummy''
	call	_atexit
	pop	ecx
	ret	0
??__Edummy@?A0xf28512a0@@YAXXZ ENDP			; `anonymous namespace'::`dynamic initializer for 'dummy''
text$di	ENDS
; Function compile flags: /Ogtp
;	COMDAT ??1initializer@?A0xf28512a0@@QAE@XZ
_TEXT	SEGMENT
??1initializer@?A0xf28512a0@@QAE@XZ PROC		; `anonymous namespace'::initializer::~initializer, COMDAT
; _this$ = ecx
; File c:\users\unm\documents\github\cacode\src\sendwaveformc\release\rcc\qrc_sendwaveformc.cpp
; Line 44
	ret	0
??1initializer@?A0xf28512a0@@QAE@XZ ENDP		; `anonymous namespace'::initializer::~initializer
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ??0initializer@?A0xf28512a0@@QAE@XZ
_TEXT	SEGMENT
??0initializer@?A0xf28512a0@@QAE@XZ PROC		; `anonymous namespace'::initializer::initializer, COMDAT
; _this$ = ecx
; File c:\users\unm\documents\github\cacode\src\sendwaveformc\release\rcc\qrc_sendwaveformc.cpp
; Line 43
	mov	eax, ecx
	ret	0
??0initializer@?A0xf28512a0@@QAE@XZ ENDP		; `anonymous namespace'::initializer::initializer
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?qCleanupResources_sendWaveformC@@YAHXZ
_TEXT	SEGMENT
?qCleanupResources_sendWaveformC@@YAHXZ PROC		; qCleanupResources_sendWaveformC, COMDAT
; File c:\users\unm\documents\github\cacode\src\sendwaveformc\release\rcc\qrc_sendwaveformc.cpp
; Line 38
	mov	eax, 1
; Line 39
	ret	0
?qCleanupResources_sendWaveformC@@YAHXZ ENDP		; qCleanupResources_sendWaveformC
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?qInitResources_sendWaveformC@@YAHXZ
_TEXT	SEGMENT
?qInitResources_sendWaveformC@@YAHXZ PROC		; qInitResources_sendWaveformC, COMDAT
; File c:\users\unm\documents\github\cacode\src\sendwaveformc\release\rcc\qrc_sendwaveformc.cpp
; Line 32
	mov	eax, 1
; Line 33
	ret	0
?qInitResources_sendWaveformC@@YAHXZ ENDP		; qInitResources_sendWaveformC
_TEXT	ENDS
END
